set_markdown:
  target:
    entity:
      integration: espaper
      domain: text
  fields:
    markdown:
      required: true
      example: "# Shopping\n\n- Milk\n- **Eggs**"
      selector:
        text:
          multiline: true

set_rotation:
  target:
    entity:
      integration: espaper
      domain: text
  fields:
    rotation:
      required: true
      example: 90
      selector:
        select:
          options: ["0", "90", "180", "270"]
